apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test
spec:
  template:
    spec:
      containers:
      - name: selenium-test
        image: tzom/webapp_testing:latest
        #image: selenium-test
        #imagePullPolicy: Never
      restartPolicy: Never